# Generated by Django 2.2 on 2021-08-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250, unique=True)),
                ('lastname', models.CharField(max_length=250, unique=True)),
                ('subject', models.TextField()),
            ],
        ),
    ]
